apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgdk-app
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default  
  source:
    path: apps/bgdk/overlays/bgdk
    repoURL: https://github.com/ovekli/openshift-gitops-examples
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
